# Copyright (c) 2023 ZRafaF
# 
# This software is released under the MIT License.
# https://opensource.org/licenses/MIT

site_name: Drone Autônomo

repo_url: https://github.com/ZRafaF/OpencvPosHold
repo_name: ZRafaF/OpencvPosHold

theme:
    name: material

    palette:
        scheme: slate
        primary: teal
        accent: teal

    locale: pt_BR
    language: pt-BR                     # lingua do mkdocs-material

    features:
        - navigation.sections
        - navigation.tabs
        # - navigation.tabs.sticky      Faz com que a navigation tab esteja sempre visivel
        - navigation.top
        - navigation.tracking
        - navigation.path
        - navigation.indexes
        - navigation.footer
        - search.highlight
        - search.share
        - search.suggest
        - toc.follow
        - content.code.copy
    icon:
        admonition:
            admonition-windows: simple/windows
            admonition-linux: simple/linux
            admonition-raspi: simple/raspberrypi
            admonition-pc: fontawesome/solid/computer

#docs_dir: 'docsSrc'
#site_dir: 'docs'

extra_css:
  - stylesheets/extra.css


plugins:
    - search:
        separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
    - with-pdf:
        author: Rafael Farias
        toc_title: Tabela de conteúdos
        enabled_if_env: ENABLE_PDF_EXPORT
        #debug_html: true
        #two_columns_level: 3
        #custom_template_path: docs/pdfTemplates
    - pdf-export:
        enabled_if_env: ENABLE_PDF_EXPORT

markdown_extensions:
    - pymdownx.highlight:
        anchor_linenums: true
        use_pygments: true      # Renderiza todos os códigos durante a build ao inves de no runtime
        auto_title: true

    - pymdownx.inlinehilite
    - pymdownx.snippets
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tilde
    - attr_list
    - md_in_html
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - toc:
        permalink: true

nav:
    - Home: 
        - index.md
        - Setup: setup.md
    
    - Utilização:
        - utilizacao/index.md
        - utilizacao/missao.md
        - utilizacao/simulacao.md

    - Hardware:
        - hardware/index.md
        - hardware/controladora_de_voo.md
        - hardware/frame.md
    
    - Software:
        - software/index.md
        - API:
            - software/api/api.md
    
    - Sobre:
        - sobre/index.md

