site_name: Drone Autônomo

repo_url: https://github.com/ZRafaF/OpencvPosHold
repo_name: ZRafaF/OpencvPosHold

theme:
    name: material

    palette:
        scheme: slate
        primary: teal
        accent: teal

    locale: pt_BR
    features:
        - navigation.sections
        - navigation.tabs
        # - navigation.tabs.sticky      Faz com que a navigation tab esteja sempre visivel
        - navigation.top
        - navigation.tracking
        - navigation.path
        - navigation.indexes
        - search.highlight
        - search.share
        - search.suggest
        - toc.follow
        - content.code.copy


#docs_dir: 'docsSrc'
#site_dir: 'docs'

plugins:
    - search:
        separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
    - with-pdf:
        author: Rafael Farias
        toc_title: Tabela de conteúdos
        #debug_html: true
        #two_columns_level: 3
        #custom_template_path: docs/styles.scss
    - pdf-export

markdown_extensions:
    - pymdownx.highlight:
        anchor_linenums: true
        use_pygments: true      # Renderiza todos os códigos durante a build ao inves de no runtime
        auto_title: true

    - pymdownx.inlinehilite
    - pymdownx.snippets
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tilde
    - attr_list
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
    - Home: index.md
    - Hardware:
        - hardware/hardware.md
        - hardware/controladora_de_voo.md
        - hardware/frame.md
    - Software:
        - software/software.md
        - API:
            - software/api/api.md

